export type GalleryItem = { src: string; cat: string; label: string; w?: number; h?: number };

export const VEHICLE_PHOTOS: GalleryItem[] = [
  { src: "/gallery/vehicles/gv-van.jpg", cat: "Our Fleet", label: "Family Van", w: 1000, h: 888 },
  { src: "/gallery/vehicles/gv-suv-1.jpg", cat: "Our Fleet", label: "SUV on Duty", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-sedan-1.jpg", cat: "Our Fleet", label: "Sedan on Duty", w: 1000, h: 888 },
  { src: "/gallery/vehicles/gv-coach.jpg", cat: "Group Tours", label: "Tourist Coach", w: 1000, h: 399 },
  { src: "/gallery/vehicles/gv-hatch.jpg", cat: "Our Fleet", label: "Compact Car", w: 1000, h: 733 },
  { src: "/gallery/vehicles/gv-tempo-int-1.jpg", cat: "Group Tours", label: "Tempo Interior", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-tempo-int-2.jpg", cat: "Group Tours", label: "Tempo Interior", w: 1000, h: 960 },
  { src: "/gallery/vehicles/gv-tempo-tv.jpg", cat: "Group Tours", label: "Tempo TV Coach", w: 1000, h: 723 },
  { src: "/gallery/vehicles/gv-tempo-light.jpg", cat: "Group Tours", label: "Tempo Light Coach", w: 1000, h: 798 },
  { src: "/gallery/vehicles/gv-tempo-1.jpg", cat: "Group Tours", label: "Tempo Traveller", w: 1000, h: 543 },
  { src: "/gallery/vehicles/gv-tempo-2.jpg", cat: "Group Tours", label: "Tempo Traveller", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-swift-1.jpg", cat: "Our Fleet", label: "Swift", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-tempo-seats.jpg", cat: "Group Tours", label: "Tempo Seats", w: 1000, h: 960 },
  { src: "/gallery/vehicles/gv-tempo-3.jpg", cat: "Group Tours", label: "Tempo Traveller", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-tempo-4.jpg", cat: "Group Tours", label: "Tempo Traveller", w: 1000, h: 543 },
  { src: "/gallery/vehicles/gv-ertiga-1.jpg", cat: "Our Fleet", label: "Ertiga", w: 1000, h: 888 },
  { src: "/gallery/vehicles/gv-swift-2.jpg", cat: "Our Fleet", label: "Swift", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-dzire.jpg", cat: "Our Fleet", label: "Swift Dzire", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-1.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 960 },
  { src: "/gallery/vehicles/gv-innova-2.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 960 },
  { src: "/gallery/vehicles/gv-sedan-black.jpg", cat: "Our Fleet", label: "Premium Sedan", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-wedding.jpg", cat: "Weddings", label: "Wedding Car", w: 1000, h: 719 },
  { src: "/gallery/vehicles/gv-innova-3.jpg", cat: "Our Fleet", label: "Innova Crysta", w: 1000, h: 902 },
  { src: "/gallery/vehicles/gv-amaze-1.jpg", cat: "Our Fleet", label: "Honda Amaze", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-4.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 730 },
  { src: "/gallery/vehicles/gv-swift-3.jpg", cat: "Our Fleet", label: "Swift", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-sedan-2.jpg", cat: "Our Fleet", label: "Sedan on Duty", w: 1000, h: 960 },
  { src: "/gallery/vehicles/gv-innova-5.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-cabin.jpg", cat: "Our Fleet", label: "Comfort Cabin", w: 1000, h: 888 },
  { src: "/gallery/vehicles/gv-etios.jpg", cat: "Our Fleet", label: "Etios", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-6.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-cabin-1.jpg", cat: "Our Fleet", label: "Innova Cabin", w: 1000, h: 676 },
  { src: "/gallery/vehicles/gv-ertiga-2.jpg", cat: "Our Fleet", label: "Ertiga", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-7.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-8.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 892 },
  { src: "/gallery/vehicles/gv-innova-cabin-2.jpg", cat: "Our Fleet", label: "Innova Cabin", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-ertiga-3.jpg", cat: "Our Fleet", label: "Ertiga", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-9.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-cabin-3.jpg", cat: "Our Fleet", label: "Innova Cabin", w: 1000, h: 964 },
  { src: "/gallery/vehicles/gv-innova-10.jpg", cat: "Our Fleet", label: "Innova Crysta", w: 1000, h: 1320 },
  { src: "/gallery/vehicles/gv-sedan-3.jpg", cat: "Our Fleet", label: "Sedan on Duty", w: 1000, h: 1329 },
  { src: "/gallery/vehicles/gv-amaze-2.jpg", cat: "Our Fleet", label: "Honda Amaze", w: 1000, h: 1326 },
  { src: "/gallery/vehicles/gv-amaze-3.jpg", cat: "Our Fleet", label: "Honda Amaze", w: 1000, h: 1323 },
  { src: "/gallery/vehicles/gv-innova-11.jpg", cat: "Our Fleet", label: "Innova", w: 1000, h: 1005 },
  { src: "/gallery/vehicles/gv-suv-2.jpg", cat: "Our Fleet", label: "SUV on Duty", w: 1000, h: 753 },
  { src: "/gallery/vehicles/gv-sedan-4.jpg", cat: "Our Fleet", label: "Sedan on Duty", w: 1000, h: 601 },
  { src: "/gallery/vehicles/gv-compact.jpg", cat: "Our Fleet", label: "Compact Car", w: 1000, h: 945 },
  { src: "/gallery/vehicles/gv-suv-3.jpg", cat: "Our Fleet", label: "SUV on Duty", w: 1000, h: 1305 },
];
